version: "3.9"
services:
    scripts:
        build: .
        image: scripts:${DAS_TAG:-latest}
        environment:
            - DAS_MONGO_HOSTNAME=${DAS_MONGO_HOSTNAME:-mongo}
            - DAS_MONGO_PORT=${DAS_MONGO_PORT:-27017}
            - DAS_MONGO_USERNAME=${DAS_MONGO_USERNAME:-mongoadmin}
            - DAS_MONGO_PASSWORD=${DAS_MONGO_PASSWORD:-das#secret}
            - DAS_REDIS_HOSTNAME=${DAS_REDIS_HOSTNAME:-redis}
            - DAS_REDIS_PORT=${DAS_REDIS_PORT:-6379}
        tty: true
        volumes:
            - ./scripts:/scripts
        links:
            - mongo
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DAS_MONGO_USERNAME:-mongoadmin}
            - MONGO_INITDB_ROOT_PASSWORD=${DAS_MONGO_PASSWORD:-das#secret}
        ports:
            - "${DAS_MONGO_PORT:-27017}:${DAS_MONGO_PORT:-27017}"
        volumes:
            - mongodbdata:/data/db
        command: mongod --port ${DAS_MONGO_PORT:-27017}
    redis:
        image: redis
        ports:
            - "6379:6379"
volumes:
    mongodbdata: {}
