version: "3.9"
services:
    scripts:
        build: .
        environment:
            - DAS_MONGO_HOSTNAME=${DAS_MONGO_HOSTNAME:-mongo}
            - DAS_MONGO_PORT=${DAS_MONGO_PORT:-27017}
        tty: true
        volumes:
            - ./scripts:/scripts
        links:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongodbdata:/data/db
volumes:
    mongodbdata: {}
